run_name: exp1_CUB_CEM
seed_everything: 42
patience: 100
adv: False

model:
  class_path: model.CEM
  init_args:
    base: resnet50
    num_classes: 200
    num_concepts: 112
    use_pretrained: False
    concept_weight: 0.01
    lr: 0.1
    optimizer: SGD
    scheduler_arg: 50
    adv_mode: True
    adv_strategy: AT
    embed_size: 16

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128
