run_name: exp1_CUB_ResNet
seed_everything: 42
patience: 30
adv: False

model:
  class_path: model.ResNet
  init_args:
    num_classes: 200
    use_pretrained: False
    lr: 0.1
    optimizer: SGD
    scheduler_arg: 20
    adv_mode: True

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128
