seed: 42
patience: 50

model: CBM
base: resnet50
use_pretrained: True
concept_weight: 0.01
lr: 0.1
scheduler_arg: 30
adv_mode: True
hidden_dim: 0
cbm_mode: hybrid # "bool", "fuzzy", "hybrid"
attacker: PGD
attacker_args:
  eps: 0.01569
  alpha: 0.001569
  steps: 10
  adv_loss: ce # "ce", "bce", "combo"
mtl_mode: normal # "normal", "equal", "ordered"

dataset: CUB
data_path: ./data
batch_size: 128
num_concepts: 112

# CEM
embed_size: 16
# VIB
vib_lambda: 0.01
# VQ
embedding_dim: 64
codebook_size: 5120
codebook_weight: 0.25
quantizer: EMA