seed: 42
gpus: auto
patience: 50
epochs: -1

model: CBM
base: resnet50
use_pretrained: True
concept_weight: 1
optimizer: SGD
optimizer_args:
  momentum: 0.9
  weight_decay: 0.00004
lr: 0.1
scheduler: ReduceLROnPlateau
scheduler_args:
  mode: max
  factor: 0.1
  patience: 30
  min_lr: 0.00001
adv_mode: adv
hidden_dim: 0
cbm_mode: hybrid # "bool", "fuzzy", "hybrid"
attacker: PGD
train_atk_args:
  steps: 7
eval_atk_args:
  steps: 10
adv_loss: ce # "ce", "bce", "combo"
mtl_mode: normal # "normal", "equal", "ordered"

dataset: CUB
data_path: ./data
batch_size: 128
resol: 224

embed_dim: 32

# VIB
vib: 0.01
# VQ
codebook_size: 5120
codebook_weight: 0.1
quantizer: EMA
# gate
use_gate: nogate
# CL
cl_weight: 0.1
# spectral
spectral_weight: 0
# adversarial invariant
trades: 0

intervene_budget: 0
max_intervene_budget: 29