group: sp
seed: 42
epochs: -1

model: CBM
base: resnet50
use_pretrained: True
concept_weight: 1
optimizer: SGD
optimizer_args:
  momentum: 0.9
  weight_decay: 0.00004
  lr: 0.1
scheduler: ReduceLROnPlateau
scheduler_args:
  mode: max
  factor: 0.1
  patience: 30
  min_lr: 0.00001
  threshold: 0.0001
plateau_args:
  monitor: "acc"
  interval: "epoch"
  frequency: 1
  strict: true
hidden_dim: 0
res_dim: 0
cbm_mode: hybrid # "bool", "fuzzy", "hybrid"
mtl_mode: normal # "normal", "equal", "ordered"
train_mode: Std

dataset: CUB
data_path: ./data
batch_size: 128
resol: 224

# cem
embed_dim: 16

# vib
vib: 0.01
