seed: 42
patience: 30

model: CBM
base: resnet50
use_pretrained: True
concept_weight: 1
lr: 0.1
scheduler_arg: 10
adv_mode: True
hidden_dim: 0
cbm_mode: hybrid
adv_loss: combo
mtl_mode: normal

dataset: CUB
data_path: ./data
batch_size: 128
num_concepts: 112

# CEM
embed_size: 16
# VIB
vib_lambda: 0.01
# VQ
embedding_dim: 64
codebook_size: 5120
codebook_weight: 0.25
quantizer: EMA