-
  trainer: "Joint"
-
  trainer: "Joint"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: True
-
  trainer: "Joint"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: "pretrained_models/resnet_train_acc_0.85_test_acc_0.74.pth"
-
  trainer: "Joint"
  use_adv: "image2label"
-
  trainer: "Joint"
  use_adv: "image2label"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: True
-
  trainer: "Joint"
  use_adv: "image2label"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: "pretrained_models/resnet_train_acc_0.85_test_acc_0.74.pth"
-
  trainer: "Sequential"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  optimizer_args:
    lr: 0.01
    momentum: 0
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: True
-
  trainer: "Sequential"
  optimizer_args:
    lr: 0.01
    momentum: 0
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: "pretrained_models/resnet_train_acc_0.85_test_acc_0.74.pth"
-
  trainer: "Sequential"
  use_adv: "image2concept"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: True
  use_adv: "image2concept"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: "pretrained_models/resnet_train_acc_0.85_test_acc_0.74.pth"
  use_adv: "image2concept"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  use_adv: "concept2label"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: True
  use_adv: "concept2label"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: "pretrained_models/resnet_train_acc_0.85_test_acc_0.74.pth"
  use_adv: "concept2label"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  use_adv: "image2concept&concept2label"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: True
  use_adv: "image2concept&concept2label"
  optimizer_args:
    lr: 0.01
    momentum: 0
-
  trainer: "Sequential"
  model_args:
    base: "resnet50"
    num_attributes: 112
    num_classes: 200
    use_pretrained: "pretrained_models/resnet_train_acc_0.85_test_acc_0.74.pth"
  use_adv: "image2concept&concept2label"
  optimizer_args:
    lr: 0.01
    momentum: 0