experiment: "xai"
seed: 42
data_path: "./data/"
dataset: "CUB"
batch_size: 64
num_workers: 8
trainer: "Sequential"
model: "CBM"
model_args:
  base: "resnet50"
  num_attributes: 112
  num_classes: 200
  use_pretrained: False
optimizer: "SGD"
optimizer_args:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
scheduler: "StepLR"
scheduler_args:
  step_size: 50
  gamma: 0.1
loss_fn: "CrossEntropyLoss"
attr_loss_fn: "BCEWithLogitsLoss"
use_imbalance_ratio: False
epochs: 4000
use_adv: "conceptpred2label" # "image2concept", "image2label", "concept2label", "conceptpred2label", "image2concept&concept2label", "image2concept&conceptpred2label", ""
use_noise: "" # "image" or "concept" or ""
attr_loss_weight: 0.01