version: 1
experiment: "xai"
seed: 42
data_path: "./data/"
dataset: "CUB"
batch_size: 64
num_workers: 8
trainer: "Joint"
model: "OldCBM"
model_args:
  base: "resnet50"
  num_attributes: 112
  num_classes: 200
  use_pretrained: False
optimizer: "SGD"
optimizer_args:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0004
scheduler: "StepLR"
scheduler_args:
  step_size: 4000
  gamma: 0.1
loss_fn: "CrossEntropyLoss"
attr_loss_fn: "BCEWithLogitsLoss"
use_imbalance_ratio: False
epochs: 4000
use_adv: ""
use_noise: ""
attr_loss_weight: 1
adv_v2v_eps: 0.3
noise_eps: 0.3
seperate_mode: "combined"