seed_everything: 42
patience: 100

model:
  class_path: model.resCBM
  init_args:
    num_concepts: 112
    num_classes: 200
    real_concepts: 112
    base: resnet50
    use_pretrained: True
    concept_weight: 0.01
    lr: 0.1
    scheduler_arg: 30
    adv_mode: False

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128
