seed_everything: 42
patience: 30

model:
  class_path: model.VCBM
  init_args:
    num_classes: 200
    num_concepts: 112
    real_concepts: 112
    base: resnet50
    use_pretrained: True
    concept_weight: 1
    lr: 0.1
    scheduler_arg: 10
    adv_mode: True
    vib_lambda: 0.1

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128
