seed_everything: 42
patience: 30

model:
  class_path: model.VCEM
  init_args:
    num_classes: 200
    num_concepts: 112
    real_concepts: 112
    base: resnet50
    use_pretrained: True
    concept_weight: 0.01
    lr: 0.1
    scheduler_arg: 15
    adv_mode: False
    vib_lambda: 0.1
    embed_size: 16

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128
