run_name: CUB_VQCBM_AT
seed_everything: 42
patience: 50

model:
  class_path: model.VQCBM
  init_args:
    base: resnet50
    num_classes: 200
    num_concepts: 112
    use_pretrained: True
    concept_weight: 10
    lr: 0.1
    optimizer: SGD
    scheduler_patience: 20
    adv_mode: True
    adv_strategy: AT
    use_concept_logits: False
    embedding_dim: 64
    codebook_size: 5120
    codebook_weight: 0.25
    quantizer: EMA

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128