seed_everything: 42
patience: 30

model:
  class_path: model.CBM
  init_args:
    num_classes: 50
    num_concepts: 85
    real_concepts: 85
    base: resnet50
    use_pretrained: True
    concept_weight: 1
    lr: 0.1
    scheduler_arg: 10
    adv_mode: True

data:
  class_path: dataset.AwA
  init_args:
    data_path: ./data/
    batch_size: 128
