run_name: exp2_CUB_ResNet
seed_everything: 42
patience: 160
adv: True

model:
  class_path: model.ResNet
  init_args:
    num_classes: 200
    use_pretrained: True
    lr: 0.1
    optimizer: SGD
    scheduler_arg: 50
    adv_mode: True

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128
