run_name: Adv_CEM_CUB
seed_everything: 42
ckpt: saved_models/CEM_CUB.ckpt
trainer:
  max_epochs: 1000
  log_every_n_steps: 1
  logger:
    class_path: aim.pytorch_lightning.AimLogger
    init_args:
      run_name: Adv_CEM_CUB
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_acc_epoch
        dirpath: checkpoints/
        filename: Adv_CEM_CUB
        save_top_k: 1
        mode: max
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_acc_epoch
        mode: max
        min_delta: 0.001
        patience: 30

model:
  class_path: model.CEM
  init_args:
    base: resnet50
    num_classes: 200
    num_concepts: 112
    step_size: [30, 60]

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128