run_name: CBM_AwA
seed_everything: 42

model:
  class_path: model.CBM
  init_args:
    base: resnet50
    num_classes: 50
    num_concepts: 85
    use_pretrained: True
    concept_weight: 1
    lr: 0.1
    optimizer: SGD
    scheduler_patience: 5

adv_hparams:
  lr: 0.1
  scheduler_patience: 50

data:
  class_path: dataset.AwA
  init_args:
    data_path: ./data/
    batch_size: 128