run_name: ResNet_CUB
seed_everything: 42

model:
  class_path: model.ResNet
  init_args:
    num_classes: 200

adv_hparams:
    num_classes: 200

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128