run_name: VCEM_CUB
seed_everything: 42

model:
  class_path: model.VCEM
  init_args:
    base: resnet50
    num_classes: 200
    num_concepts: 112

adv_hparams:
  step_size: [30, 60]

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128