method: random
metric:
  goal: maximize
  name: val_acc
parameters:
  concept_weight:
    values: [0.01, 0.1, 1, 10]
  num_concepts:
    values: [32, 64, 112, 128, 256]
  adv_mode:
    values: [True, False]
  embed_size:
    values: [8, 16, 32, 64]