- model: backbone
  dataset: CUB
  base: resnet50
  adv_mode: std
  optimizer_args:
    momentum: 0
    weight_decay: 0
- model: CBM
  dataset: CUB
  base: resnet50
  adv_mode: std
- model: VCBM
  dataset: CUB
  base: resnet50
  adv_mode: std

- model: backbone
  dataset: CUB
  base: resnet50
  adv_mode: adv
  atk_target: label
  optimizer_args:
    momentum: 0
    weight_decay: 0
- model: CBM
  dataset: CUB
  base: resnet50
  adv_mode: adv
  atk_target: label
- model: CBM
  dataset: CUB
  base: resnet50
  adv_mode: adv
  atk_target: concept
- model: CBM
  dataset: CUB
  base: resnet50
  adv_mode: adv
  atk_target: combined
- model: VCBM
  dataset: CUB
  base: resnet50
  adv_mode: adv
  atk_target: label
- model: VCBM
  dataset: CUB
  base: resnet50
  adv_mode: adv
  atk_target: label
  vib: 0.1