run_name: CUB_CEM_AT
seed_everything: 42
patience: 30

model:
  class_path: model.CEM
  init_args:
    base: resnet50
    num_classes: 200
    num_concepts: 112
    use_pretrained: True
    concept_weight: 10
    lr: 0.1
    optimizer: SGD
    scheduler_patience: 15
    adv_mode: True
    adv_strategy: AT
    embed_size: 16

data:
  class_path: dataset.CUB
  init_args:
    data_path: ./data
    batch_size: 128
